# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
repos:
  CRAN: https://cloud.r-project.org
  PIK:  https://rse.pik-potsdam.de/r/packages/
cache: packages
latex: false
pandoc: false
sudo: false
install:
  - Rscript -e "install.packages('testthat');install.packages('lucode')"
script:
  - Rscript ./tests/testthat/test-travisCI.R
